### ISSUE TITLE
Couldn't get it working with Spree 2.0.x

### ISSUE THREAD

**Issue by suyashtripathi** [joshnuss/spree-html-email#11]
I'm using Spree 2.0.5 Beta. 

Gem installation gave issues for which I made few changes updating the dependencies on pre mailer and spree-core gems. I was able to install the gem afterwards but don't see it working with the spree. Spree is still picking the same old text templates. 

Is there anything else that needs to be changed or taken care of? Want to make it working but am pretty clueless as of now.

**Comment by iloveitaly** [comment]
My store isn't on 2.x yet, so I haven't tested spree-html-email with that version yet.

Checkout others' branches (for example, [this branch](https://github.com/motioneleven/spree-html-email/) seems to have some 2.x work done on it) and see what changes others have made. If you are able to get this extension working with 2.x submit a PR! Thanks :)

**Comment by suyashtripathi** [comment]
Thank you so much Michael. It was very helpful. The branch needed few minor fixes though, which I did on [my branch](https://github.com/suyashtripathi/spree-html-email). Did some initial testing, found it to be working fine.

**Comment by iloveitaly** [comment]
Great @suyashtripathi! Feel free to submit a PR after you clean things up on your end!
