### ISSUE TITLE
Wrong date in sent email

### ISSUE THREAD

**Issue by msevestre** [joshnuss/spree-html-email#6]
Hi there,
The `completed at` date in the order section reads in my example `2012-10-08`
However on the html email, it reads `Submitted  November 08, 2012` which clearly the wrong date. (october vs november)

That is due to that line of code
https://github.com/joshnuss/spree-html-email/blob/master/app/views/spree/shared/email/_order_details.html.erb#L18

I am not sure what's wrong with it. Any hints would be appreciated

Cheers,
Michael

**Comment by msevestre** [comment]
Anyone here with some idea what the date is wrong? That's a pretty annoying bug. Happy to make a PR if I get some hint at what to correct
Thanks

**Comment by msevestre** [comment]
Well I found the issue .to_date is missing.

**Comment by joshnuss** [comment]
I fixed it, thanks for the heads up!

**Comment by msevestre** [comment]
cool thanks
