### ISSUE TITLE
Doesn't work with Spree-1-3-stable

### ISSUE THREAD

**Issue by Lordnibbler** [joshnuss/spree-html-email#7]
Using Ruby 1.9.3-p194 and Rails 3.2.13, I get the following error upon running rails server

``` ruby
gems/spree_html_email-0.70.2/app/mailers/order_mailer_decorator.rb:1:in `<top (required)>': uninitialized constant OrderMailer (NameError)
```

**Comment by joshnuss** [comment]
Thanks for reporting. My plan is to update to spree 1-3 the next time I use it. If you want to submit a patch I'd work with you to get it in

**Comment by Lordnibbler** [comment]
Sure, going to  try and get it working.  I noticed in my error above I seem to be using a dated version of the gem.  Looking at rubygems.org, I see the newest version is `0.70.2` but on your github the newest version is `1.0.0` according to your `.gemspec`.

**Comment by Lordnibbler** [comment]
OK, all that needs to be done is edit your `spree_html_email.gemspec` file's line to:  `s.add_dependency 'spree_core', '~> 1.3.0'`

Sorry, my pull request contains some CSS tweaks too -- If you merge in my master up to this commit it works without any CSS tweaks: https://github.com/Lordnibbler/spree-html-email/commit/414e5514a71b331796222fa674c581718ed6c8ec

414e5514a71b331796222fa674c581718ed6c8ec

Ps is there an easier way to override CSS in this gem?

**Comment by joshnuss** [comment]
Thanks @Lordnibbler 

You should be able to override that template in your host app.

The reason the CSS in an html template is because i never could figure out how to get the asset pipeline to work with the premailer gem. maybe i should investigate that again

**Comment by iloveitaly** [comment]
Added [1-3-stable branch](https://github.com/joshnuss/spree-html-email/commits/1-3-stable) for 1.3.x compatibility.

To get the email.css to work in production you have to add `config.assets.precompile += %w( store/email.css )` to your `production.rb`
